name: Build and Deploy

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:
    - uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specifies the Node.js version

    - name: Install dependencies
      run: npm install  # Installs project dependencies

    - name: Create .env file
      run: |
        echo API_KEY=${{ secrets.API_KEY }} > .env
      # Creates a .env file with the API key from GitHub Secrets

    - name: Build the app
      run: npm run build
      # Replace 'npm run build' with your build command

    # - name: Deploy the app
    #   run: <your-deployment-command>
      # Replace '<your-deployment-command>' with your deployment process

    # Additional steps like testing, caching, or notifications can be added here
